version: "3.8"
services:
    dock-angular:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:80"
        container_name: dock-angular
        volumes:  
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf